name: Terraform Backend Validation

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Day-90

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE }}
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - run: terraform fmt -check
      - run: terraform validate

      - name: Terraform Init
        run: |
          terraform init \
            -input=false \
            -backend-config="key=ci/${{ github.run_id }}.tfstate"

      - run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan

