name: Terraform Backend Validation

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  terraform-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Day-90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials Action for GitHub Actions"
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838v   #v5.0.0 
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE}}
          aws-region: ap-south-1

      - name: HashiCorp - Setup 
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36  #v3.0.0
        with:
          terraform_version: "1.1.7"


      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
